language: swift

osx_image: xcode11.3
env:
  matrix:
    - TEST_SDK=iphonesimulator13.2 OS=13.1 NAME='iPhone 11 Pro Max'
    - TEST_SDK=iphonesimulator13.2 OS=12.1 NAME='iPhone 7 Plus'

script:
    - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project TLLoadingButton.xcodeproj -scheme TLLoadingButton -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES
after_success:
    - slather
    - bash <(curl -s https://codecov.io/bash) -f reports/cobertura.xml -X coveragepy -X gcov -X xcode

